### ISSUE TITLE
Can you make "illegal" (not dead) rows orange please?

### ISSUE THREAD

**Issue by andrew-buchanan** [miguel-ambrona/deadpos#33]
There are 4 kinds of row that appear after r command:
red "illegal dead"
red "illegal" (alive)
yellow (legal) "dead"
green "" (legal, alive)

Yes?

The second row, could that be orange please?

**Comment by miguel-ambrona** [comment]
Hi Andrew.
Version 2.3 (still WIP) now introduced the notion of "zombie", so I believe the above is obsolete.

We now have three classes of positions:
 - _illegal_: same as FIDE (no game following the rules can reach the position).
 - _zombie_: legal, but all possible restractions are dead.
 -  legal and not zombie (a reachable position following the mobility rules + DP).
 
 Note that the "dead" keyword is an orthogonal notion (it indicates that the position is dead when this is relevant, because it is either the result of a retraction or the middle of a longer forward sequence).

**Comment by andrew-buchanan** [comment]
Hi thanks for this.

So, there are 5 different statuses possible. Currently each of them is identified separately, but the colours of (1)&(2) are the same.

(1) FIDE illegal + dead (red)
(2) FIDE illegal + living (red)
(3) FIDE legal + zombie (blue)
(4) FIDE legal + dead (yellow)
(5) FIDE legal + living (green)

I would still like (2) to be orange, please, because it's kind of a retro try.

Note "dead" is not *quite* orthogonal to your 3 bullets, because zombie can only be dead, not living.

**Comment by miguel-ambrona** [comment]
I'll use magenta as orange is not available.

I still support the idea that the term "dead" is independent.

When analyzing legality, the current position is not analyzed to be dead.
The fact that zombie implies dead is a nice subtlety derived from the fact that from dead one cannot reach alive.

Consider the following example.
```
>>> K7/2k5/8/8/8/8/8/8 ? >>= legal
K7/2k5/8/8/8/8/8/8 w - - ? 1                                                    
zombie K7/2k5/8/8/8/8/8/8 b - - ? 1                                             
nsols 1
```
Here the liveness of the given position (either WTM or BTM) has never been explicitly analyzed (because it does not come from a retraction in the stipulation). Still, it has been labeled as zombie, because it is FIDE legal, but all the FIDE legal retractions are dead.
